### ISSUE TITLE
Use as sidebar in admin panel

### ISSUE THREAD

**Issue by denisdulici** [nWidart/laravel-menus#7]
Hi,

Is there any reason you're not using this package as the sidebar of AsgardCMS ?

Regards

**Comment by nWidart** [comment]
Hi,

Just because we use the laravel-sidebar package which is easy to manage via php and is in version control.

**Comment by denisdulici** [comment]
I did the same with your package, via PHP, extensible as within Asgard, through events 😉

**Comment by nWidart** [comment]
I see, interesting. So it's manageable via the UI and code? What if I have a menu item via code, but client removes it via the UI?

**Comment by denisdulici** [comment]
I'm not talking about the Menu manager of Asgard but the Admin Sidebar, which managed from code of modules. Like this one:
https://github.com/AsgardCms/Platform/blob/2.0/Modules/Page/Events/Handlers/RegisterPageSidebar.php

**Comment by denisdulici** [comment]
Mine is something like this: https://gist.github.com/denisdulici/9883b81b1440ae8cb4026ac498fd92d5

**Comment by nWidart** [comment]
The menu manager of asgard is this package, to which you PR'ed the adminlte presenter. So  I assume it's for the backend. Same as your title here.

So based on your code, what happens when the clients removes that item?
I assume that item wouldn't be persisted in the database so the client can't even touch it? What's the upside of using it then vs laravel-sidebar?

**Comment by denisdulici** [comment]
In Asgard, as far as I know, the admin sidebar is not saved in database and there is no UI for it so the client can't touch it, right?

As for the upside, why use 2 packages when you can get the same with 1 ?

**Comment by nWidart** [comment]
I see yea that makes sense.

**Comment by nWidart** [comment]
I'll close this as your PR was merged. 😄
